### ISSUE TITLE
Using tfsec to validate that all helm_release resources use the version arguement

### ISSUE THREAD

**Issue by stephengroat** [andreswebs/eks-tf#1]
https://github.com/andreswebs/eks-tf/blob/31892f70ef7b511747ed4dbd7a3f9705bf97be20/modules/k8s-monitoring/main.tf#L36

to assure build consistency

**Comment by andreswebs** [comment]
closed by https://github.com/andreswebs/eks-tf/commit/bf5fd3d2199712cecbba05a8342ce2d3a31d9c28
