### ISSUE TITLE
using tfsec to detect json vs aws_iam_policy_document data

### ISSUE THREAD

**Issue by stephengroat** [andreswebs/eks-tf#2]
https://github.com/andreswebs/eks-tf/blob/31892f70ef7b511747ed4dbd7a3f9705bf97be20/modules/k8s-aws-efs-csi-driver/main.tf#L37

seems pedantic, but I waste so much time fixing people's `json` mistakes

**Comment by andreswebs** [comment]
closed by https://github.com/andreswebs/eks-tf/commit/ce3c6f08cae28ce195cb8bf5c2f4a54369f21782
